---
- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: name=nginx state=present

- name: Add group www
  group: name=www

- name: Add user www
  user: name=www group=www shell=/sbin/nologin

- name: Create nginx log dir
  file: path=/ssd/www/zencart/weblogs state=directory owner=www group=www

- name: Copy nginx configuration for common
  template: src=nginx.conf dest=/etc/nginx/nginx.conf backup=yes
  notify: restart nginx
