---
- name: Install Sysconfig, Nginx, and PHP-FPM
  hosts: td-servers
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - sysconf
    - common
    - nginx
    - php-fpm
