---
- name: install nodejs {{ nodejs_version }} to {{ nodejs_install_dir }}
  command: cp -r /usr/local/src/node-v{{ nodejs_version }}-linux-x64 {{ nodejs_install_dir }}
  args:
    creates: '{{ nodejs_install_dir }}'

- name: setup nodejs ENV path {{ nodejs_install_dir }}/bin 
  blockinfile:
    dest: /etc/profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK - nodejs"
    insertbefore: '^export PATH USER'
    backup: yes
    content: |
      NODE_HOME={{ nodejs_install_dir }}
      export PATH=$NODE_HOME/bin:$PATH
  tags:
    - nodejs_setup_env_path

