---
## Installation options
redis_version: 3.2.6
redis_checksum: 0c7bc5c751bdbc6fabed178db9cdbdd948915d1b
redis_install_dir: /usr/local/redis
redis_dir: /var/lib/redis/{{ redis_port }}
redis_download_url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"

redis_user: redis
redis_group: "{{ redis_user }}"

## Networking/connection options
redis_bind: 0.0.0.0
redis_port: 6379
redis_password: qa_qredis_test_pw


## Replication options
# Set slaveof just as you would in redis.conf. (e.g. "redis01 6379")
redis_slaveof: false
# Make slaves read-only. "yes" or "no"
redis_slave_read_only: "yes"
redis_slave_priority: 100
redis_repl_backlog_size: false

## Logging
redis_logdir: /var/log/redis
redis_logfile: "{{ redis_logdir }}/redis_{{ redis_port }}.log"

## General configuration
redis_daemonize: "yes"
redis_piddir: /var/run/redis
redis_pidfile: "{{ redis_piddir }}/{{ redis_port }}.pid"
# Number of databases to allow
redis_databases: 16
redis_loglevel: notice
# Log queries slower than this many milliseconds. -1 to disable
redis_slowlog_log_slower_than: 10000
# Maximum number of slow queries to save
redis_slowlog_max_len: 128
# Redis memory limit (e.g. 4294967296, 4096mb, 4gb)
redis_maxmemory: false
redis_maxmemory_policy: noeviction
redis_rename_commands: []
# How frequently to snapshot the database to disk
# e.g. "900 1" => 900 seconds if at least 1 key changed
redis_save:
  - 900 1
  - 300 10
  - 60 10000
