---
- name: include role java
  include_role:
    name: java

- name: download Tomcat
  get_url:
      url: http://apache.website-solution.net/tomcat/tomcat-7/v7.0.75/bin/apache-tomcat-7.0.75.tar.gz
      dest: /usr/local/src/apache-tomcat-7.0.75.tar.gz
      checksum: "sha1:1373d27e7e9cd4c481b4b17c6b2c36aff157b66e"

- name: extract archive
  unarchive:
    src: /usr/local/src/apache-tomcat-7.0.75.tar.gz
    dest: /usr/local/src
    creates: /usr/local/src/apache-tomcat-7.0.75
    copy: no

- name: copy Tomcat to install dir
  command: cp -r /usr/local/src/apache-tomcat-7.0.75 /opt/apache-tomcat-7.0.75
  args:
    creates: /opt/apache-tomcat-7.0.75
  notify: start tomcat

